### ISSUE TITLE
Error in Text.changeWord

### ISSUE THREAD

**Issue by juergen123** [bombardellif/acrostics-generator#12]
How to reproduce: 
run the Algorithm with the "FriedrichDerGrosse" Text and and required acrostic "Fritz".

ORIGINAL TEXT:
Friedrich wurde im Berliner Stadtschloss geboren und war der älteste
überlebende Sohn von insgesamt 14 Kindern König Friedrich Wilhelms I.
und dessen Gattin Sophie Dorothea, der ersten hochadligen Königin des
Fürstentums zu Hannover.

==========
==========

Exception in thread "main" java.lang.IllegalArgumentException: changeWord: Invalid word position
	at controller.Text.changeWord(Text.java:325)
	at controller.SynonymOperation.changeForSynonym(SynonymOperation.java:85)
	at controller.SynonymOperation.execute(SynonymOperation.java:27)
	at model.Algorithm.execute(Algorithm.java:105)
	at controller.Main.main(Main.java:244)
Java Result: 1
BUILD SUCCESSFUL (total time: 5 seconds)

**Comment by wbombardellis** [comment]
It seems like I've fixed this. Here is the output for the given input:
(I remember you that the synonym operation is not taking into account the context (nGram), that's why it generated such result)
>>>>>>>>>>>>>>>>>>>>>>>>>
ORIGINAL TEXT:
Friedrich wurde im Berliner Stadtschloss geboren und war der älteste
überlebende Sohn von insgesamt 14 Kindern König Friedrich Wilhelms I.
und dessen Gattin Sophie Dorothea, der ersten hochadligen Königin des
Fürstentums zu Hannover.
....
...
.

The Algorithm Result:

Friedrich wurde im Berliner Stadtschloss geboren ein Üb-
riges tun war der älteste überlebende Sohn von insgesamt 14 K-
indern König Friedrich Wilhelms I. und dessen Gattin Sophie Doro-
thea, der ersten hochadligen Königin des Fürstentums 
zu Hannover.

Print Operator List:
controller.SynonymOperation@3bcfebf6
HyphenationOperation
HyphenationOperation
controller.WrongHyphenationOperation@6a6f9b32
LineBreakOperation

Number Generated Nodes: 77390
BUILD SUCCESSFUL (total time: 5 minutes 42 seconds)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
