### ISSUE TITLE
Hyphenation Problem

### ISSUE THREAD

**Issue by wbombardellis** [bombardellif/acrostics-generator#13]
How to reproduce: Actual version of algorithm with these operators:
-LineBreak
-Wrong Hyphenation
-Word Insertion and Deletion
-Hyphenation

Text: Vorstellen.txt
Acrostic: amte

ORIGINAL TEXT:
Ah ja, ich heisse Frederik Hoske und ich bin 13 Jahre. Ich kann nicht
vorstellen, weil ich kein Deutsch kann. Trotzden versuche ich es. Ich
habe zwei Geschwister Mein Bruder der 16 Jahre alt ist und meine
Schweseter ist elf. Äh die heissen ... Mein Bruder ist Erik und meine
Schwester Charlotte. Mein Land ... also ich lebe in Deutschland. Meine
Mutter ist aus der dominikanischen Republik.

......
....
.

The Algorithm Result:

Ah ja, ich heisse Frederik Hoske und ich bin 13 _Jah- re_. Ich kann
mir nicht vorstellen, weil ich kein Deutsch kann.
Trotzden versuche ich es. Ich habe zwei Geschwister Mein Bruder der
16 Jahre alt ist und meine Schweseter ist elf. Äh die heissen ... Mein
Bruder ist Erik und meine Schwester Charlotte. Mein Land ... also ich
lebe in Deutschland. Meine Mutter ist aus der dominikanischen
Republik.

Print Operator List:
HyphenationOperation
LineBreakOperation
controller.WordInsertionDeletionOperation@76e1ad79

Number Generated Nodes: 14112
BUILD SUCCESSFUL (total time: 1 minute 32 seconds)

**Comment by bombardellif** [comment]
Duplicate #5

**Comment by juergen123** [comment]
Hi all,


on the bug with the hyphenation: i think it don't has to be threaded, because when the
acrostic can be generated, this is done from TOP to BOTTOM. So at the end we
get the acrostic or not.

In general it is not clear to me what should happen, to avoid that the deletion of 
earlier operations. E.g. when there was a line break in line 3 and then comes a line break in
line 1.  In principle the line break could appear again or it must be deleted. Anyway,
i don't see why an operation that was already executed should be reverted.

I hope for testing, the hyphenation/linebreak as it is now will be sufficient. Otherwise, let
me know that we find a solution.

Regards
Jürgen 

 


--------------------------------------------
Fernando Bombardelli da Silva <notifications@github.com> schrieb am Mi, 21.1.2015:

 Betreff: Re: [acrostics-generator] Hyphenation Problem (#13)
 An: "bombardellif/acrostics-generator" <acrostics-generator@noreply.github.com>
 Datum: Mittwoch, 21. Januar, 2015 01:57 Uhr
 
 Duplicate #5
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by wbombardellis** [comment]
Jürgen, I agree with you.

But the problem here is not about deleting previous executed operation. Instead the problem lies on the word "Jah- re" in the middle of the first line.

Doesn't it damage the final result?

**Comment by juergen123** [comment]
William, i tried again to reproduce the example, without success

Text: Vorstellen.txt
Acrostic: amte

including only: LineBreak,WordInsertionDeletion,WrongHyphenation, Hyphenation

What i get is:

ORIGINAL TEXT:
Ah ja, ich heisse Frederik Hoske und ich bin 13 Jahre. Ich kann nicht
vorstellen, weil ich kaum Deutsch sprechen kann. Trotzdem versuche ich
es. Ich habe zwei Geschwister Mein Bruder der 16 Jahre alt ist und
meine Schweseter ist elf. Äh die heissen ... Mein Bruder ist Erik und
meine Schwester Charlotte. Mein Land ... also ich lebe in Deutschland.
Meine Mutter ist aus der dominikanischen Republik.


The Algorithm Result:

Ah ja, ich heisse Frederik Hoske und ich bin 13 Jahre. Ich kann
mir nicht vorstellen, weil ich kaum Deutsch sprechen kann.
Trotzdem versuche ich es. Ich habe zwei Geschwister Mein Bruder d-
er 16 Jahre alt ist und meine Schweseter ist elf. Äh die heissen ... Mein
Bruder ist Erik und meine Schwester Charlotte. Mein Land ... also ich
lebe in Deutschland. Meine Mutter ist aus der dominikanischen
Republik.

Print Operator List:
LineBreakOperation
controller.WordInsertionDeletionOperation@5a8cbffe
LineBreakOperation
controller.WrongHyphenationOperation@96a75da

Number Generated Nodes: 1026
BUILD SUCCESSFUL (total time: 23 seconds)

Perhaps there where problems with the internet connection while you did the computation, 
such that NetSpeakApi didn't works well.

Regards
Jürgen









 

--------------------------------------------
William Bombardelli da Silva <notifications@github.com> schrieb am Mi, 21.1.2015:

 Betreff: Re: [acrostics-generator] Hyphenation Problem (#13)
 An: "bombardellif/acrostics-generator" <acrostics-generator@noreply.github.com>
 CC: "juergen123" <jurgenbauer71@yahoo.de>
 Datum: Mittwoch, 21. Januar, 2015 10:27 Uhr
 
 Jürgen, I agree with you.
 
 But the problem here is not about deleting previous
 executed operation. Instead the problem lies on the word
 "Jah- re" in the middle of the first line.
 
 Doesn't it damage the final result?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by wbombardellis** [comment]
Hm ok. Maybe the error is not reproductable with this text anymore. But the fault is still there. See issue #5 for example or other duplicate issues.

The fault lies on the case in which there is an hyphenated word in the end of the line and a line break occurs just before this last word. Making the this last word (hyphenated with the "-" symbol) to go down to the next line.

Maybe if you print every produced text during the execution you'll see the error.

Regards, William

**Comment by juergen123** [comment]
yes, when printing out each single text then the error is visible. But the error exactly appears,
when e.g. first an operation in the 3rd line is executed before an operation in the 1st line. And this path
anyway is not a solution path and therefore not relevant for generating the acrostic. Actually the only
solution i see right now, it to trust that if the acrostic is generable then this could be done by a letterwise
top-to-bottom procedure. 

--------------------------------------------
William Bombardelli da Silva <notifications@github.com> schrieb am Mi, 21.1.2015:

 Betreff: Re: [acrostics-generator] Hyphenation Problem (#13)
 An: "bombardellif/acrostics-generator" <acrostics-generator@noreply.github.com>
 CC: "juergen123" <jurgenbauer71@yahoo.de>
 Datum: Mittwoch, 21. Januar, 2015 11:56 Uhr
 
 Hm ok. Maybe the error is not
 reproductable with this text anymore. But the fault is still
 there. See issue #5
 for example or other duplicate issues.
 
 The fault lies on the case in which there is an
 hyphenated word in the end of the line and a line break
 occurs just before this last word. Making the this last word
 (hyphenated with the "-" symbol) to go down to the
 next line.
 
 Maybe if you print every produced text during the
 execution you'll see the error.
 
 Regards, William
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by wbombardellis** [comment]
Ah ok I got you point.
Well, once it doesn't seem to happen in the solution I'm turning this into a enhancement issue.

**Comment by bombardellif** [comment]
Closing because of fix see #5
